### ISSUE TITLE
WinError 1314

### ISSUE THREAD

**Issue by wongpor** [if-ai/ComfyUI-IF_AI_WishperSpeechNode#1]
Error occurred when executing IF_WhisperSpeech:

[WinError 1314] A required privilege is not held by the client: 'C:\\Users\\x\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\eac27266f68caa806381260bd44ace38b136c76a\\hyperparams.yaml' -> '~\\.cache\\speechbrain\\hyperparams.yaml'

File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_WishperSpeechNode\IFWhisperSpeechNode.py", line 98, in generate_audio
speaker = pipe.extract_spk_emb(speaker_file_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\whisperspeech\pipeline.py", line 76, in extract_spk_emb
self.encoder = EncoderClassifier.from_hparams("speechbrain/spkrec-ecapa-voxceleb",
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\speechbrain\pretrained\interfaces.py", line 467, in from_hparams
hparams_local_path = fetch(
^^^^^^
File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\speechbrain\pretrained\fetching.py", line 181, in fetch
destination.symlink_to(sourcepath)
File "pathlib.py", line 1198, in symlink_to

**Comment by if-ai** [comment]
It looks like a huggingfacehub issue sorry I might forgotten add it as requirement, it looks like is trying to download the models but you don't have a hugging face token already in your machine. I will update th requirement

**Comment by if-ai** [comment]
You might need to change the policy in windows to allow non admins to create symlinks on the system
WhisperSpeech is trying to download the models on the hugging Face hub location in your drive and then creating symlinks to point to the models but you have enough access rights as a user on that machine

You can try run comfy as admin at least to create the symlinks to download this models
you can give privileges to this user just to install the models and then revert the policy back to the original after the link is created 

This is How ChatGPT says how to do it
# Solutions to Resolve Permission Issues for Symlink Creation

## Run as Administrator
- **Run your Python script or the command prompt/terminal you are using as an administrator.** This gives your script the necessary privileges to create symlinks.
- Right-click on your command prompt or terminal shortcut and select "Run as administrator".
- Execute your Python script from this elevated command prompt.

## Enable Symlink Creation for Non-Administrators
- On Windows, you can change a security policy to allow non-administrative users to create symbolic links:
  - Open the **Local Security Policy** editor (you can search for `secpol.msc` in the Start menu).
  - Navigate to **Local Policies** -> **User Rights Assignment**.
  - Double-click on **Create symbolic links**.
  - Add your user to the list, or a group your user belongs to.
  - Log out and log back in for the changes to take effect.

## Check User Account Control Settings
- Sometimes, User Account Control (UAC) settings can interfere with symlink creation. You might consider adjusting these settings, though be cautious as lowering security settings can make your system more vulnerable.

I also added Huggingfacehub to the reqs now but that is not the issue is more your user has no access to create symlinks

**Comment by wongpor** [comment]
i try to run the workflow sample, and tried edit Permission Issues for Symlink Creation, it run a little bit more, but still got error, i cant find which file i was missing.

Error occurred when executing IF_DreamTalk:

[WinError 2] The system cannot find the file specified

File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFDreamTalkNode.py", line 136, in run
wav_16k_path = self.convert_to_16k(audio_input, output_name, tmp_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFDreamTalkNode.py", line 95, in convert_to_16k
sample_rate = subprocess.check_output(command.split()).decode().strip()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "subprocess.py", line 466, in check_output
File "subprocess.py", line 548, in run
File "subprocess.py", line 1026, in __init__
File "subprocess.py", line 1538, in _execute_child
